import * as React from "react"
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header.js";
import { Footer } from "./components/footer";
import { ThemeProvider, useTheme } from "next-themes";
import { ThemeBody } from "./components/body-theme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeBody>
            <Header/>
            {children}
            <Footer/>
          </ThemeBody>    
        </ThemeProvider>
      </body>
    </html>
  );
}
